Add 8-bit Level Shifter [TXB0108]
olin-electric-motorsports/OEM_Preferred_Parts pull request #194
Opened 2020-11-16 21:14 UTC by nonas-hunter

Creating a new component for an 8-bit level shifter to be used on the SD Card CAN Logger PCB.

[Link to Digi-Key](https://www.digikey.com/en/products/detail/texas-instruments/TXB0108PWR/1305699l)

2020-11-16 21:18 UTC, jack-greenberg commented
Digikey link is broken @nonas-hunter

2020-11-16 21:50 UTC, nonas-hunter commented
Link should be fixed! @jack-greenberg

2020-11-17 01:52 UTC, ljordan51 requested changes
I need a little more time to look at the actual symbol, gotta switch computers so just publishing this review for now

2020-11-17 01:52 UTC, ljordan51 commented on schematic/formula.dcm
> +D Voltage level translator, 4-channel, bidirectional, TSSOP-14
is it not 8-channel?

2020-11-17 01:52 UTC, ljordan51 commented on schematic/formula.dcm
> +D Voltage level translator, 4-channel, bidirectional, TSSOP-14
and I think it's TSSOP-20 right?

2020-11-17 02:11 UTC, ljordan51 commented
okay everything looks good, just address the inline comments above and then this can be merged

2020-11-17 02:18 UTC, nonas-hunter commented on schematic/formula.dcm
> +D Voltage level translator, 4-channel, bidirectional, TSSOP-14
You are so right -- totally missed that. I'll fix that now.

2020-11-17 02:22 UTC, nonas-hunter commented
@ljordan51 -- Changes were just made to the comment! Is there anything else that needs to be addressed?

Also, how did you do that awesome suggestion box?

2020-11-17 02:25 UTC, ljordan51 approved these changes

2020-11-17 02:25 UTC, ljordan51 commented
haha you hover the mouse just to the right of the line number and a blue plus sign pops up which you can click on to leave an inline comment

2020-11-17 02:25 UTC, merged

2020-11-17 02:26 UTC, ljordan51 commented
you have to be in the "Files Changed" or "Commits" view where you can see the actual code